/// `colorui` 图标库
/// wget -O fonts/iconfont.ttf https://at.alicdn.com/t/font_1656945_d66u4pxvlq6.ttf
/// gist: https://gist.github.com/d1y/64b2098dac30be4d47aaac2f1a7d8149
library colorui;
import 'package:flutter/widgets.dart';
class CuIcons {
  static const String _family = 'cufont';
  static const String _pkg = 'colorui';
  CuIcons._();
  static const IconData aa =
      IconData(0xe7a1, fontFamily: _family, fontPackage: _pkg);
  static const IconData accounts =
      IconData(0xe681, fontFamily: _family, fontPackage: _pkg);
  static const IconData accountsO =
      IconData(0xe686, fontFamily: _family, fontPackage: _pkg);
  static const IconData add =
      IconData(0xe6e4, fontFamily: _family, fontPackage: _pkg);
  static const IconData addRound =
      IconData(0xe717, fontFamily: _family, fontPackage: _pkg);
  static const IconData addRoundO =
      IconData(0xe718, fontFamily: _family, fontPackage: _pkg);
  static const IconData alarm =
      IconData(0xe61e, fontFamily: _family, fontPackage: _pkg);
  static const IconData album =
      IconData(0xe759, fontFamily: _family, fontPackage: _pkg);
  static const IconData alipay =
      IconData(0xe6e1, fontFamily: _family, fontPackage: _pkg);
  static const IconData android =
      IconData(0xe6e2, fontFamily: _family, fontPackage: _pkg);
  static const IconData angle =
      IconData(0xe605, fontFamily: _family, fontPackage: _pkg);
  static const IconData apple =
      IconData(0xe8e7, fontFamily: _family, fontPackage: _pkg);
  static const IconData apps =
      IconData(0xe737, fontFamily: _family, fontPackage: _pkg);
  static const IconData archive =
      IconData(0xe7ae, fontFamily: _family, fontPackage: _pkg);
  static const IconData archiveO =
      IconData(0xe7ad, fontFamily: _family, fontPackage: _pkg);
  static const IconData arrow =
      IconData(0xe608, fontFamily: _family, fontPackage: _pkg);
  static const IconData atLine =
      IconData(0xe75c, fontFamily: _family, fontPackage: _pkg);
  static const IconData avatar =
      IconData(0xe663, fontFamily: _family, fontPackage: _pkg);
  static const IconData avatarO =
      IconData(0xe665, fontFamily: _family, fontPackage: _pkg);
  static const IconData avatars =
      IconData(0xe67e, fontFamily: _family, fontPackage: _pkg);
  static const IconData avatarsO =
      IconData(0xe680, fontFamily: _family, fontPackage: _pkg);
  static const IconData back =
      IconData(0xe600, fontFamily: _family, fontPackage: _pkg);
  static const IconData backspace =
      IconData(0xe6a9, fontFamily: _family, fontPackage: _pkg);
  static const IconData backup =
      IconData(0xe61f, fontFamily: _family, fontPackage: _pkg);
  static const IconData backupRestore =
      IconData(0xe62d, fontFamily: _family, fontPackage: _pkg);
  static const IconData barcode =
      IconData(0xe71f, fontFamily: _family, fontPackage: _pkg);
  static const IconData book =
      IconData(0xe6a2, fontFamily: _family, fontPackage: _pkg);
  static const IconData bookmark =
      IconData(0xe6a3, fontFamily: _family, fontPackage: _pkg);
  static const IconData bookmarkO =
      IconData(0xe697, fontFamily: _family, fontPackage: _pkg);
  static const IconData bookmarks =
      IconData(0xe6a6, fontFamily: _family, fontPackage: _pkg);
  static const IconData box =
      IconData(0xe714, fontFamily: _family, fontPackage: _pkg);
  static const IconData boxBlock =
      IconData(0xe6ac, fontFamily: _family, fontPackage: _pkg);
  static const IconData boxRight =
      IconData(0xe6a0, fontFamily: _family, fontPackage: _pkg);
  static const IconData brand =
      IconData(0xe726, fontFamily: _family, fontPackage: _pkg);
  static const IconData brandO =
      IconData(0xe727, fontFamily: _family, fontPackage: _pkg);
  static const IconData building =
      IconData(0xe6c3, fontFamily: _family, fontPackage: _pkg);
  static const IconData buildingO =
      IconData(0xe6c7, fontFamily: _family, fontPackage: _pkg);
  static const IconData camera =
      IconData(0xe6fa, fontFamily: _family, fontPackage: _pkg);
  static const IconData cameraAdd =
      IconData(0xe736, fontFamily: _family, fontPackage: _pkg);
  static const IconData cameraAddO =
      IconData(0xe735, fontFamily: _family, fontPackage: _pkg);
  static const IconData cameraLens =
      IconData(0xe68f, fontFamily: _family, fontPackage: _pkg);
  static const IconData cameraLensO =
      IconData(0xe68e, fontFamily: _family, fontPackage: _pkg);
  static const IconData cameraO =
      IconData(0xe6fb, fontFamily: _family, fontPackage: _pkg);
  static const IconData cameraRotate =
      IconData(0xe71e, fontFamily: _family, fontPackage: _pkg);
  static const IconData card =
      IconData(0xe744, fontFamily: _family, fontPackage: _pkg);
  static const IconData cardboard =
      IconData(0xe7a9, fontFamily: _family, fontPackage: _pkg);
  static const IconData cardboardO =
      IconData(0xe7aa, fontFamily: _family, fontPackage: _pkg);
  static const IconData cardboardOffO =
      IconData(0xe7af, fontFamily: _family, fontPackage: _pkg);
  static const IconData cart =
      IconData(0xe70b, fontFamily: _family, fontPackage: _pkg);
  static const IconData cartO =
      IconData(0xe708, fontFamily: _family, fontPackage: _pkg);
  static const IconData chat =
      IconData(0xe739, fontFamily: _family, fontPackage: _pkg);
  static const IconData chatBubble =
      IconData(0xe69b, fontFamily: _family, fontPackage: _pkg);
  static const IconData chatBubbleO =
      IconData(0xe6a7, fontFamily: _family, fontPackage: _pkg);
  static const IconData chatList =
      IconData(0xe69d, fontFamily: _family, fontPackage: _pkg);
  static const IconData chatListO =
      IconData(0xe6aa, fontFamily: _family, fontPackage: _pkg);
  static const IconData chatO =
      IconData(0xe73c, fontFamily: _family, fontPackage: _pkg);
  static const IconData chatSmile =
      IconData(0xe779, fontFamily: _family, fontPackage: _pkg);
  static const IconData chatSmileO =
      IconData(0xe78e, fontFamily: _family, fontPackage: _pkg);
  static const IconData chatSmiles =
      IconData(0xe76b, fontFamily: _family, fontPackage: _pkg);
  static const IconData chatSmilesO =
      IconData(0xe74a, fontFamily: _family, fontPackage: _pkg);
  static const IconData check =
      IconData(0xe69f, fontFamily: _family, fontPackage: _pkg);
  static const IconData checkbox =
      IconData(0xe713, fontFamily: _family, fontPackage: _pkg);
  static const IconData checkboxO =
      IconData(0xe715, fontFamily: _family, fontPackage: _pkg);
  static const IconData checkRound =
      IconData(0xe6f1, fontFamily: _family, fontPackage: _pkg);
  static const IconData checkRoundO =
      IconData(0xe6f2, fontFamily: _family, fontPackage: _pkg);
  static const IconData choiceness =
      IconData(0xe728, fontFamily: _family, fontPackage: _pkg);
  static const IconData choicenessO =
      IconData(0xe729, fontFamily: _family, fontPackage: _pkg);
  static const IconData chrome =
      IconData(0xe6e3, fontFamily: _family, fontPackage: _pkg);
  static const IconData circle =
      IconData(0xe7b0, fontFamily: _family, fontPackage: _pkg);
  static const IconData circleO =
      IconData(0xe7b1, fontFamily: _family, fontPackage: _pkg);
  static const IconData close =
      IconData(0xe6ed, fontFamily: _family, fontPackage: _pkg);
  static const IconData closeRound =
      IconData(0xe6f3, fontFamily: _family, fontPackage: _pkg);
  static const IconData closeRoundO =
      IconData(0xe6f4, fontFamily: _family, fontPackage: _pkg);
  static const IconData clothes =
      IconData(0xe72a, fontFamily: _family, fontPackage: _pkg);
  static const IconData clothesO =
      IconData(0xe72b, fontFamily: _family, fontPackage: _pkg);
  static const IconData cloud =
      IconData(0xe64e, fontFamily: _family, fontPackage: _pkg);
  static const IconData cloudDone =
      IconData(0xe641, fontFamily: _family, fontPackage: _pkg);
  static const IconData cloudDownload =
      IconData(0xe647, fontFamily: _family, fontPackage: _pkg);
  static const IconData cloudO =
      IconData(0xe646, fontFamily: _family, fontPackage: _pkg);
  static const IconData cloudOff =
      IconData(0xe64b, fontFamily: _family, fontPackage: _pkg);
  static const IconData cloudUpload =
      IconData(0xe687, fontFamily: _family, fontPackage: _pkg);
  static const IconData codeBox =
      IconData(0xe7c3, fontFamily: _family, fontPackage: _pkg);
  static const IconData coin =
      IconData(0xe78a, fontFamily: _family, fontPackage: _pkg);
  static const IconData coinO =
      IconData(0xe79d, fontFamily: _family, fontPackage: _pkg);
  static const IconData comment =
      IconData(0xe738, fontFamily: _family, fontPackage: _pkg);
  static const IconData commentO =
      IconData(0xe70e, fontFamily: _family, fontPackage: _pkg);
  static const IconData community =
      IconData(0xe742, fontFamily: _family, fontPackage: _pkg);
  static const IconData communityO =
      IconData(0xe743, fontFamily: _family, fontPackage: _pkg);
  static const IconData countdown =
      IconData(0xe722, fontFamily: _family, fontPackage: _pkg);
  static const IconData countdownO =
      IconData(0xe723, fontFamily: _family, fontPackage: _pkg);
  static const IconData creative =
      IconData(0xe72c, fontFamily: _family, fontPackage: _pkg);
  static const IconData creativeO =
      IconData(0xe72d, fontFamily: _family, fontPackage: _pkg);
  static const IconData crop =
      IconData(0xe6d9, fontFamily: _family, fontPackage: _pkg);
  static const IconData crown =
      IconData(0xe776, fontFamily: _family, fontPackage: _pkg);
  static const IconData crownO =
      IconData(0xe777, fontFamily: _family, fontPackage: _pkg);
  static const IconData cut =
      IconData(0xe74b, fontFamily: _family, fontPackage: _pkg);
  static const IconData darkmode =
      IconData(0xe7c4, fontFamily: _family, fontPackage: _pkg);
  static const IconData dashboard =
      IconData(0xe62e, fontFamily: _family, fontPackage: _pkg);
  static const IconData delete =
      IconData(0xe6bd, fontFamily: _family, fontPackage: _pkg);
  static const IconData deleteClose =
      IconData(0xe6ae, fontFamily: _family, fontPackage: _pkg);
  static const IconData deleteLine =
      IconData(0xe707, fontFamily: _family, fontPackage: _pkg);
  static const IconData deleteLineO =
      IconData(0xe709, fontFamily: _family, fontPackage: _pkg);
  static const IconData deleteO =
      IconData(0xe69a, fontFamily: _family, fontPackage: _pkg);
  static const IconData deliver =
      IconData(0xe7f7, fontFamily: _family, fontPackage: _pkg);
  static const IconData deliverO =
      IconData(0xe6ff, fontFamily: _family, fontPackage: _pkg);
  static const IconData demo =
      IconData(0xe916, fontFamily: _family, fontPackage: _pkg);
  static const IconData discover =
      IconData(0xe70c, fontFamily: _family, fontPackage: _pkg);
  static const IconData discoverO =
      IconData(0xe702, fontFamily: _family, fontPackage: _pkg);
  static const IconData discussFill =
      IconData(0xe790, fontFamily: _family, fontPackage: _pkg);
  static const IconData discussLine =
      IconData(0xe78f, fontFamily: _family, fontPackage: _pkg);
  static const IconData dollar =
      IconData(0xe79f, fontFamily: _family, fontPackage: _pkg);
  static const IconData dollarO =
      IconData(0xe79e, fontFamily: _family, fontPackage: _pkg);
  static const IconData done =
      IconData(0xe633, fontFamily: _family, fontPackage: _pkg);
  static const IconData doneAll =
      IconData(0xe62a, fontFamily: _family, fontPackage: _pkg);
  static const IconData douyin =
      IconData(0xe6e7, fontFamily: _family, fontPackage: _pkg);
  static const IconData dropDown =
      IconData(0xe61c, fontFamily: _family, fontPackage: _pkg);
  static const IconData dropUp =
      IconData(0xe61d, fontFamily: _family, fontPackage: _pkg);
  static const IconData eject =
      IconData(0xe63a, fontFamily: _family, fontPackage: _pkg);
  static const IconData ellipse =
      IconData(0xe74c, fontFamily: _family, fontPackage: _pkg);
  static const IconData emoji =
      IconData(0xe78d, fontFamily: _family, fontPackage: _pkg);
  static const IconData emojiO =
      IconData(0xe6ee, fontFamily: _family, fontPackage: _pkg);
  static const IconData equalizer =
      IconData(0xe802, fontFamily: _family, fontPackage: _pkg);
  static const IconData eraser =
      IconData(0xe770, fontFamily: _family, fontPackage: _pkg);
  static const IconData eraserO =
      IconData(0xe772, fontFamily: _family, fontPackage: _pkg);
  static const IconData evaluate =
      IconData(0xe7f0, fontFamily: _family, fontPackage: _pkg);
  static const IconData evaluateO =
      IconData(0xe700, fontFamily: _family, fontPackage: _pkg);
  static const IconData eventClose =
      IconData(0xe6a5, fontFamily: _family, fontPackage: _pkg);
  static const IconData eventDone =
      IconData(0xe6b2, fontFamily: _family, fontPackage: _pkg);
  static const IconData eventList =
      IconData(0xe6b8, fontFamily: _family, fontPackage: _pkg);
  static const IconData explore =
      IconData(0xe628, fontFamily: _family, fontPackage: _pkg);
  static const IconData exploreLine =
      IconData(0xe719, fontFamily: _family, fontPackage: _pkg);
  static const IconData exploreLineO =
      IconData(0xe710, fontFamily: _family, fontPackage: _pkg);
  static const IconData exploreO =
      IconData(0xe626, fontFamily: _family, fontPackage: _pkg);
  static const IconData extension =
      IconData(0xe620, fontFamily: _family, fontPackage: _pkg);
  static const IconData extensionO =
      IconData(0xe63f, fontFamily: _family, fontPackage: _pkg);
  static const IconData eye =
      IconData(0xe740, fontFamily: _family, fontPackage: _pkg);
  static const IconData eyeFavor =
      IconData(0xe7b4, fontFamily: _family, fontPackage: _pkg);
  static const IconData eyeFavorO =
      IconData(0xe7b5, fontFamily: _family, fontPackage: _pkg);
  static const IconData eyeO =
      IconData(0xe741, fontFamily: _family, fontPackage: _pkg);
  static const IconData eyeOff =
      IconData(0xe7b3, fontFamily: _family, fontPackage: _pkg);
  static const IconData eyeOffO =
      IconData(0xe7b2, fontFamily: _family, fontPackage: _pkg);
  static const IconData facebook =
      IconData(0xe6ea, fontFamily: _family, fontPackage: _pkg);
  static const IconData favorite =
      IconData(0xe623, fontFamily: _family, fontPackage: _pkg);
  static const IconData favoriteO =
      IconData(0xe621, fontFamily: _family, fontPackage: _pkg);
  static const IconData female =
      IconData(0xe72f, fontFamily: _family, fontPackage: _pkg);
  static const IconData file =
      IconData(0xe857, fontFamily: _family, fontPackage: _pkg);
  static const IconData fileCopy =
      IconData(0xe85c, fontFamily: _family, fontPackage: _pkg);
  static const IconData fileCopyO =
      IconData(0xe7bc, fontFamily: _family, fontPackage: _pkg);
  static const IconData fileO =
      IconData(0xe7bb, fontFamily: _family, fontPackage: _pkg);
  static const IconData fileText =
      IconData(0xe858, fontFamily: _family, fontPackage: _pkg);
  static const IconData fileTextO =
      IconData(0xe7b9, fontFamily: _family, fontPackage: _pkg);
  static const IconData filter =
      IconData(0xe6ec, fontFamily: _family, fontPackage: _pkg);
  static const IconData fingerprint =
      IconData(0xe63b, fontFamily: _family, fontPackage: _pkg);
  static const IconData firstPage =
      IconData(0xe60c, fontFamily: _family, fontPackage: _pkg);
  static const IconData flag =
      IconData(0xe64d, fontFamily: _family, fontPackage: _pkg);
  static const IconData flagO =
      IconData(0xe64c, fontFamily: _family, fontPackage: _pkg);
  static const IconData flashClose =
      IconData(0xe73b, fontFamily: _family, fontPackage: _pkg);
  static const IconData flashOff =
      IconData(0xe6d5, fontFamily: _family, fontPackage: _pkg);
  static const IconData flashOn =
      IconData(0xe6dc, fontFamily: _family, fontPackage: _pkg);
  static const IconData flashOpen =
      IconData(0xe74f, fontFamily: _family, fontPackage: _pkg);
  static const IconData folder =
      IconData(0xe6a1, fontFamily: _family, fontPackage: _pkg);
  static const IconData folderAdd =
      IconData(0xe6b4, fontFamily: _family, fontPackage: _pkg);
  static const IconData folderO =
      IconData(0xe6b0, fontFamily: _family, fontPackage: _pkg);
  static const IconData folderSpecial =
      IconData(0xe65c, fontFamily: _family, fontPackage: _pkg);
  static const IconData forward =
      IconData(0xe601, fontFamily: _family, fontPackage: _pkg);
  static const IconData fullscreen =
      IconData(0xe915, fontFamily: _family, fontPackage: _pkg);
  static const IconData fullscreenExit =
      IconData(0xe914, fontFamily: _family, fontPackage: _pkg);
  static const IconData game =
      IconData(0xe6c0, fontFamily: _family, fontPackage: _pkg);
  static const IconData gameO =
      IconData(0xe6d1, fontFamily: _family, fontPackage: _pkg);
  static const IconData gitCommit =
      IconData(0xe7be, fontFamily: _family, fontPackage: _pkg);
  static const IconData gitCommitO =
      IconData(0xe7bd, fontFamily: _family, fontPackage: _pkg);
  static const IconData github =
      IconData(0xe6e9, fontFamily: _family, fontPackage: _pkg);
  static const IconData githubCircle =
      IconData(0xead8, fontFamily: _family, fontPackage: _pkg);
  static const IconData goods =
      IconData(0xe778, fontFamily: _family, fontPackage: _pkg);
  static const IconData goodsnew =
      IconData(0xe7bf, fontFamily: _family, fontPackage: _pkg);
  static const IconData goodsnewO =
      IconData(0xe7c0, fontFamily: _family, fontPackage: _pkg);
  static const IconData goodsO =
      IconData(0xe70f, fontFamily: _family, fontPackage: _pkg);
  static const IconData googleplaylogo =
      IconData(0xe6e5, fontFamily: _family, fontPackage: _pkg);
  static const IconData grid =
      IconData(0xe6ce, fontFamily: _family, fontPackage: _pkg);
  static const IconData gridO =
      IconData(0xe6cc, fontFamily: _family, fontPackage: _pkg);
  static const IconData group =
      IconData(0xe7f5, fontFamily: _family, fontPackage: _pkg);
  static const IconData groupO =
      IconData(0xe753, fontFamily: _family, fontPackage: _pkg);
  static const IconData guanli =
      IconData(0xe750, fontFamily: _family, fontPackage: _pkg);
  static const IconData headset =
      IconData(0xe6a4, fontFamily: _family, fontPackage: _pkg);
  static const IconData headsetMic =
      IconData(0xe6b1, fontFamily: _family, fontPackage: _pkg);
  static const IconData help =
      IconData(0xe66b, fontFamily: _family, fontPackage: _pkg);
  static const IconData helpO =
      IconData(0xe65e, fontFamily: _family, fontPackage: _pkg);
  static const IconData home =
      IconData(0xe70d, fontFamily: _family, fontPackage: _pkg);
  static const IconData home2 =
      IconData(0xe6fd, fontFamily: _family, fontPackage: _pkg);
  static const IconData home2O =
      IconData(0xe6cf, fontFamily: _family, fontPackage: _pkg);
  static const IconData home3 =
      IconData(0xe6fc, fontFamily: _family, fontPackage: _pkg);
  static const IconData home3O =
      IconData(0xe6e0, fontFamily: _family, fontPackage: _pkg);
  static const IconData home4 =
      IconData(0xe732, fontFamily: _family, fontPackage: _pkg);
  static const IconData home4O =
      IconData(0xe6e6, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeCommunity =
      IconData(0xe799, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeDot =
      IconData(0xe794, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeDotO =
      IconData(0xe797, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeLine =
      IconData(0xe793, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeLineO =
      IconData(0xe792, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeO =
      IconData(0xe70a, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeSm =
      IconData(0xe798, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeSmile =
      IconData(0xe79c, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeSmileO =
      IconData(0xe7a0, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeSmline =
      IconData(0xe791, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeSmlineO =
      IconData(0xe731, fontFamily: _family, fontPackage: _pkg);
  static const IconData homeSmO =
      IconData(0xe79b, fontFamily: _family, fontPackage: _pkg);
  static const IconData hotel =
      IconData(0xe7a8, fontFamily: _family, fontPackage: _pkg);
  static const IconData hotelO =
      IconData(0xe7a3, fontFamily: _family, fontPackage: _pkg);
  static const IconData huohu =
      IconData(0xe72e, fontFamily: _family, fontPackage: _pkg);
  static const IconData ie =
      IconData(0xe922, fontFamily: _family, fontPackage: _pkg);
  static const IconData imageText =
      IconData(0xe781, fontFamily: _family, fontPackage: _pkg);
  static const IconData imageTextO =
      IconData(0xe758, fontFamily: _family, fontPackage: _pkg);
  static const IconData importExport =
      IconData(0xe615, fontFamily: _family, fontPackage: _pkg);
  static const IconData info =
      IconData(0xe6ef, fontFamily: _family, fontPackage: _pkg);
  static const IconData infoO =
      IconData(0xe705, fontFamily: _family, fontPackage: _pkg);
  static const IconData input =
      IconData(0xe75f, fontFamily: _family, fontPackage: _pkg);
  static const IconData inputO =
      IconData(0xe6c8, fontFamily: _family, fontPackage: _pkg);
  static const IconData keyboard =
      IconData(0xe6b6, fontFamily: _family, fontPackage: _pkg);
  static const IconData kinds =
      IconData(0xe748, fontFamily: _family, fontPackage: _pkg);
  static const IconData lastPage =
      IconData(0xe60d, fontFamily: _family, fontPackage: _pkg);
  static const IconData layout =
      IconData(0xe7e8, fontFamily: _family, fontPackage: _pkg);
  static const IconData layoutO =
      IconData(0xe7e7, fontFamily: _family, fontPackage: _pkg);
  static const IconData lightmode =
      IconData(0xe7ba, fontFamily: _family, fontPackage: _pkg);
  static const IconData link =
      IconData(0xe6ab, fontFamily: _family, fontPackage: _pkg);
  static const IconData linkOff =
      IconData(0xe6b9, fontFamily: _family, fontPackage: _pkg);
  static const IconData loaderFill =
      IconData(0xe76d, fontFamily: _family, fontPackage: _pkg);
  static const IconData loading =
      IconData(0xe746, fontFamily: _family, fontPackage: _pkg);
  static const IconData loading1 =
      IconData(0xe749, fontFamily: _family, fontPackage: _pkg);
  static const IconData loading2 =
      IconData(0xe7f1, fontFamily: _family, fontPackage: _pkg);
  static const IconData locationOff =
      IconData(0xe671, fontFamily: _family, fontPackage: _pkg);
  static const IconData locationOffO =
      IconData(0xe66d, fontFamily: _family, fontPackage: _pkg);
  static const IconData locationOn =
      IconData(0xe65f, fontFamily: _family, fontPackage: _pkg);
  static const IconData locationOnO =
      IconData(0xe661, fontFamily: _family, fontPackage: _pkg);
  static const IconData lock =
      IconData(0xe6ad, fontFamily: _family, fontPackage: _pkg);
  static const IconData lockO =
      IconData(0xe6b3, fontFamily: _family, fontPackage: _pkg);
  static const IconData lockOpen =
      IconData(0xe6ba, fontFamily: _family, fontPackage: _pkg);
  static const IconData logout =
      IconData(0xe76e, fontFamily: _family, fontPackage: _pkg);
  static const IconData loop =
      IconData(0xe616, fontFamily: _family, fontPackage: _pkg);
  static const IconData magic =
      IconData(0xe6b7, fontFamily: _family, fontPackage: _pkg);
  static const IconData magicO =
      IconData(0xe6c2, fontFamily: _family, fontPackage: _pkg);
  static const IconData mail =
      IconData(0xe6be, fontFamily: _family, fontPackage: _pkg);
  static const IconData mailO =
      IconData(0xe6bc, fontFamily: _family, fontPackage: _pkg);
  static const IconData male =
      IconData(0xe730, fontFamily: _family, fontPackage: _pkg);
  static const IconData mic =
      IconData(0xe656, fontFamily: _family, fontPackage: _pkg);
  static const IconData micNone =
      IconData(0xe642, fontFamily: _family, fontPackage: _pkg);
  static const IconData micOff =
      IconData(0xe652, fontFamily: _family, fontPackage: _pkg);
  static const IconData miniprogram =
      IconData(0xe7d6, fontFamily: _family, fontPackage: _pkg);
  static const IconData mobile =
      IconData(0xe854, fontFamily: _family, fontPackage: _pkg);
  static const IconData mobileO =
      IconData(0xe7b6, fontFamily: _family, fontPackage: _pkg);
  static const IconData moneybag =
      IconData(0xe7ce, fontFamily: _family, fontPackage: _pkg);
  static const IconData moneybagO =
      IconData(0xe7d1, fontFamily: _family, fontPackage: _pkg);
  static const IconData more =
      IconData(0xe688, fontFamily: _family, fontPackage: _pkg);
  static const IconData moreTag =
      IconData(0xe672, fontFamily: _family, fontPackage: _pkg);
  static const IconData move =
      IconData(0xe768, fontFamily: _family, fontPackage: _pkg);
  static const IconData moveRound =
      IconData(0xe602, fontFamily: _family, fontPackage: _pkg);
  static const IconData moveRoundO =
      IconData(0xe603, fontFamily: _family, fontPackage: _pkg);
  static const IconData music =
      IconData(0xe795, fontFamily: _family, fontPackage: _pkg);
  static const IconData musicOff =
      IconData(0xe796, fontFamily: _family, fontPackage: _pkg);
  static const IconData my =
      IconData(0xe78c, fontFamily: _family, fontPackage: _pkg);
  static const IconData myO =
      IconData(0xe78b, fontFamily: _family, fontPackage: _pkg);
  static const IconData nearMe =
      IconData(0xe654, fontFamily: _family, fontPackage: _pkg);
  static const IconData nearMeO =
      IconData(0xe649, fontFamily: _family, fontPackage: _pkg);
  static const IconData not =
      IconData(0xe667, fontFamily: _family, fontPackage: _pkg);
  static const IconData notice =
      IconData(0xe666, fontFamily: _family, fontPackage: _pkg);
  static const IconData noticeActive =
      IconData(0xe66f, fontFamily: _family, fontPackage: _pkg);
  static const IconData noticeActiveO =
      IconData(0xe65d, fontFamily: _family, fontPackage: _pkg);
  static const IconData noticeO =
      IconData(0xe664, fontFamily: _family, fontPackage: _pkg);
  static const IconData noticeOff =
      IconData(0xe6b5, fontFamily: _family, fontPackage: _pkg);
  static const IconData noticeOffO =
      IconData(0xe6bb, fontFamily: _family, fontPackage: _pkg);
  static const IconData numcode =
      IconData(0xe755, fontFamily: _family, fontPackage: _pkg);
  static const IconData order =
      IconData(0xe786, fontFamily: _family, fontPackage: _pkg);
  static const IconData orderO =
      IconData(0xe7b8, fontFamily: _family, fontPackage: _pkg);
  static const IconData paint =
      IconData(0xe75d, fontFamily: _family, fontPackage: _pkg);
  static const IconData paintO =
      IconData(0xe75a, fontFamily: _family, fontPackage: _pkg);
  static const IconData palette =
      IconData(0xe696, fontFamily: _family, fontPackage: _pkg);
  static const IconData paletteO =
      IconData(0xe691, fontFamily: _family, fontPackage: _pkg);
  static const IconData pause =
      IconData(0xe669, fontFamily: _family, fontPackage: _pkg);
  static const IconData pauseCircle =
      IconData(0xe678, fontFamily: _family, fontPackage: _pkg);
  static const IconData person =
      IconData(0xe679, fontFamily: _family, fontPackage: _pkg);
  static const IconData personAdd =
      IconData(0xe668, fontFamily: _family, fontPackage: _pkg);
  static const IconData personAddO =
      IconData(0xe66a, fontFamily: _family, fontPackage: _pkg);
  static const IconData personO =
      IconData(0xe67d, fontFamily: _family, fontPackage: _pkg);
  static const IconData personPinCircle =
      IconData(0xe66c, fontFamily: _family, fontPackage: _pkg);
  static const IconData personPinCircleO =
      IconData(0xe670, fontFamily: _family, fontPackage: _pkg);
  static const IconData phone =
      IconData(0xe6f0, fontFamily: _family, fontPackage: _pkg);
  static const IconData phoneCall =
      IconData(0xe6d7, fontFamily: _family, fontPackage: _pkg);
  static const IconData pic =
      IconData(0xe756, fontFamily: _family, fontPackage: _pkg);
  static const IconData picO =
      IconData(0xe69e, fontFamily: _family, fontPackage: _pkg);
  static const IconData pinDrop =
      IconData(0xe648, fontFamily: _family, fontPackage: _pkg);
  static const IconData pinDropO =
      IconData(0xe655, fontFamily: _family, fontPackage: _pkg);
  static const IconData place =
      IconData(0xe651, fontFamily: _family, fontPackage: _pkg);
  static const IconData placeO =
      IconData(0xe650, fontFamily: _family, fontPackage: _pkg);
  static const IconData playArrow =
      IconData(0xe66e, fontFamily: _family, fontPackage: _pkg);
  static const IconData playCircle =
      IconData(0xe674, fontFamily: _family, fontPackage: _pkg);
  static const IconData playCircleO =
      IconData(0xe67f, fontFamily: _family, fontPackage: _pkg);
  static const IconData popover =
      IconData(0xe74e, fontFamily: _family, fontPackage: _pkg);
  static const IconData popoverO =
      IconData(0xe757, fontFamily: _family, fontPackage: _pkg);
  static const IconData present =
      IconData(0xe73a, fontFamily: _family, fontPackage: _pkg);
  static const IconData presentO =
      IconData(0xe711, fontFamily: _family, fontPackage: _pkg);
  static const IconData progress =
      IconData(0xe784, fontFamily: _family, fontPackage: _pkg);
  static const IconData qq =
      IconData(0xe7d9, fontFamily: _family, fontPackage: _pkg);
  static const IconData qrCodeFill =
      IconData(0xe767, fontFamily: _family, fontPackage: _pkg);
  static const IconData qrCodeLine =
      IconData(0xe75e, fontFamily: _family, fontPackage: _pkg);
  static const IconData quill =
      IconData(0xe760, fontFamily: _family, fontPackage: _pkg);
  static const IconData quillO =
      IconData(0xe761, fontFamily: _family, fontPackage: _pkg);
  static const IconData radio =
      IconData(0xe6d4, fontFamily: _family, fontPackage: _pkg);
  static const IconData radiobox =
      IconData(0xe763, fontFamily: _family, fontPackage: _pkg);
  static const IconData radioboxO =
      IconData(0xe75b, fontFamily: _family, fontPackage: _pkg);
  static const IconData recharge =
      IconData(0xe71c, fontFamily: _family, fontPackage: _pkg);
  static const IconData rechargeO =
      IconData(0xe71d, fontFamily: _family, fontPackage: _pkg);
  static const IconData record =
      IconData(0xe7a4, fontFamily: _family, fontPackage: _pkg);
  static const IconData recordO =
      IconData(0xe7a6, fontFamily: _family, fontPackage: _pkg);
  static const IconData redo =
      IconData(0xe612, fontFamily: _family, fontPackage: _pkg);
  static const IconData redpacket =
      IconData(0xe7d3, fontFamily: _family, fontPackage: _pkg);
  static const IconData redpacketO =
      IconData(0xe71a, fontFamily: _family, fontPackage: _pkg);
  static const IconData refresh =
      IconData(0xe611, fontFamily: _family, fontPackage: _pkg);
  static const IconData repair =
      IconData(0xe73f, fontFamily: _family, fontPackage: _pkg);
  static const IconData repairO =
      IconData(0xe73e, fontFamily: _family, fontPackage: _pkg);
  static const IconData repeat =
      IconData(0xe617, fontFamily: _family, fontPackage: _pkg);
  static const IconData replay =
      IconData(0xe619, fontFamily: _family, fontPackage: _pkg);
  static const IconData reply =
      IconData(0xe618, fontFamily: _family, fontPackage: _pkg);
  static const IconData replyAll =
      IconData(0xe614, fontFamily: _family, fontPackage: _pkg);
  static const IconData roadMap =
      IconData(0xe769, fontFamily: _family, fontPackage: _pkg);
  static const IconData roadMapO =
      IconData(0xe76a, fontFamily: _family, fontPackage: _pkg);
  static const IconData round =
      IconData(0xe716, fontFamily: _family, fontPackage: _pkg);
  static const IconData roundAngle =
      IconData(0xe6f5, fontFamily: _family, fontPackage: _pkg);
  static const IconData roundAngleO =
      IconData(0xe6f6, fontFamily: _family, fontPackage: _pkg);
  static const IconData roundArrowLine =
      IconData(0xe734, fontFamily: _family, fontPackage: _pkg);
  static const IconData roundBox =
      IconData(0xe604, fontFamily: _family, fontPackage: _pkg);
  static const IconData safe =
      IconData(0xe77f, fontFamily: _family, fontPackage: _pkg);
  static const IconData safeCheck =
      IconData(0xe875, fontFamily: _family, fontPackage: _pkg);
  static const IconData safeCheckO =
      IconData(0xe876, fontFamily: _family, fontPackage: _pkg);
  static const IconData safeFlash =
      IconData(0xe783, fontFamily: _family, fontPackage: _pkg);
  static const IconData safeFlashO =
      IconData(0xe775, fontFamily: _family, fontPackage: _pkg);
  static const IconData safeKey =
      IconData(0xe76c, fontFamily: _family, fontPackage: _pkg);
  static const IconData safeKeyO =
      IconData(0xe766, fontFamily: _family, fontPackage: _pkg);
  static const IconData safeO =
      IconData(0xe77e, fontFamily: _family, fontPackage: _pkg);
  static const IconData save =
      IconData(0xe677, fontFamily: _family, fontPackage: _pkg);
  static const IconData saveO =
      IconData(0xe684, fontFamily: _family, fontPackage: _pkg);
  static const IconData scan =
      IconData(0xe703, fontFamily: _family, fontPackage: _pkg);
  static const IconData scissors =
      IconData(0xe762, fontFamily: _family, fontPackage: _pkg);
  static const IconData search =
      IconData(0xe6f7, fontFamily: _family, fontPackage: _pkg);
  static const IconData searchLine =
      IconData(0xe771, fontFamily: _family, fontPackage: _pkg);
  static const IconData searchlist =
      IconData(0xe720, fontFamily: _family, fontPackage: _pkg);
  static const IconData searchO =
      IconData(0xe782, fontFamily: _family, fontPackage: _pkg);
  static const IconData searchSm =
      IconData(0xe631, fontFamily: _family, fontPackage: _pkg);
  static const IconData service =
      IconData(0xe73d, fontFamily: _family, fontPackage: _pkg);
  static const IconData serviceFill =
      IconData(0xe704, fontFamily: _family, fontPackage: _pkg);
  static const IconData serviceO =
      IconData(0xe721, fontFamily: _family, fontPackage: _pkg);
  static const IconData set =
      IconData(0xe773, fontFamily: _family, fontPackage: _pkg);
  static const IconData setList =
      IconData(0xe76f, fontFamily: _family, fontPackage: _pkg);
  static const IconData setO =
      IconData(0xe774, fontFamily: _family, fontPackage: _pkg);
  static const IconData settings =
      IconData(0xe77a, fontFamily: _family, fontPackage: _pkg);
  static const IconData settingsO =
      IconData(0xe780, fontFamily: _family, fontPackage: _pkg);
  static const IconData share =
      IconData(0xe6c5, fontFamily: _family, fontPackage: _pkg);
  static const IconData shareLineO =
      IconData(0xe74d, fontFamily: _family, fontPackage: _pkg);
  static const IconData shengji =
      IconData(0xe747, fontFamily: _family, fontPackage: _pkg);
  static const IconData shoppingCart =
      IconData(0xe685, fontFamily: _family, fontPackage: _pkg);
  static const IconData shoppingCartO =
      IconData(0xe676, fontFamily: _family, fontPackage: _pkg);
  static const IconData show =
      IconData(0xe785, fontFamily: _family, fontPackage: _pkg);
  static const IconData showO =
      IconData(0xe787, fontFamily: _family, fontPackage: _pkg);
  static const IconData shuffle =
      IconData(0xe61a, fontFamily: _family, fontPackage: _pkg);
  static const IconData sip =
      IconData(0xe764, fontFamily: _family, fontPackage: _pkg);
  static const IconData sipO =
      IconData(0xe765, fontFamily: _family, fontPackage: _pkg);
  static const IconData skipNext =
      IconData(0xe6dd, fontFamily: _family, fontPackage: _pkg);
  static const IconData skipPrevious =
      IconData(0xe6d6, fontFamily: _family, fontPackage: _pkg);
  static const IconData slack =
      IconData(0xe87b, fontFamily: _family, fontPackage: _pkg);
  static const IconData slackSquare =
      IconData(0xe891, fontFamily: _family, fontPackage: _pkg);
  static const IconData sort =
      IconData(0xe6bf, fontFamily: _family, fontPackage: _pkg);
  static const IconData sortOrder =
      IconData(0xe6fe, fontFamily: _family, fontPackage: _pkg);
  static const IconData sound =
      IconData(0xe77b, fontFamily: _family, fontPackage: _pkg);
  static const IconData sponsor =
      IconData(0xe77c, fontFamily: _family, fontPackage: _pkg);
  static const IconData sponsorO =
      IconData(0xe77d, fontFamily: _family, fontPackage: _pkg);
  static const IconData star =
      IconData(0xe683, fontFamily: _family, fontPackage: _pkg);
  static const IconData starHalf =
      IconData(0xe67c, fontFamily: _family, fontPackage: _pkg);
  static const IconData starO =
      IconData(0xe67b, fontFamily: _family, fontPackage: _pkg);
  static const IconData stock =
      IconData(0xe789, fontFamily: _family, fontPackage: _pkg);
  static const IconData stop =
      IconData(0xe6db, fontFamily: _family, fontPackage: _pkg);
  static const IconData store =
      IconData(0xe7ac, fontFamily: _family, fontPackage: _pkg);
  static const IconData store0 =
      IconData(0xe7ab, fontFamily: _family, fontPackage: _pkg);
  static const IconData store2 =
      IconData(0xe7a7, fontFamily: _family, fontPackage: _pkg);
  static const IconData store2O =
      IconData(0xe7a5, fontFamily: _family, fontPackage: _pkg);
  static const IconData subLeft =
      IconData(0xe60b, fontFamily: _family, fontPackage: _pkg);
  static const IconData subRight =
      IconData(0xe60f, fontFamily: _family, fontPackage: _pkg);
  static const IconData subtitles =
      IconData(0xe6da, fontFamily: _family, fontPackage: _pkg);
  static const IconData subtitlesO =
      IconData(0xe6d8, fontFamily: _family, fontPackage: _pkg);
  static const IconData syncAlt =
      IconData(0xe613, fontFamily: _family, fontPackage: _pkg);
  static const IconData tag =
      IconData(0xe751, fontFamily: _family, fontPackage: _pkg);
  static const IconData tagO =
      IconData(0xe752, fontFamily: _family, fontPackage: _pkg);
  static const IconData taobao =
      IconData(0xe712, fontFamily: _family, fontPackage: _pkg);
  static const IconData terminal =
      IconData(0xe7c1, fontFamily: _family, fontPackage: _pkg);
  static const IconData terminalO =
      IconData(0xe7c2, fontFamily: _family, fontPackage: _pkg);
  static const IconData thumbDown =
      IconData(0xe6c1, fontFamily: _family, fontPackage: _pkg);
  static const IconData thumbDownO =
      IconData(0xe6c9, fontFamily: _family, fontPackage: _pkg);
  static const IconData thumbUp =
      IconData(0xe6c6, fontFamily: _family, fontPackage: _pkg);
  static const IconData thumbUpLine =
      IconData(0xe71b, fontFamily: _family, fontPackage: _pkg);
  static const IconData thumbUpLineO =
      IconData(0xe6eb, fontFamily: _family, fontPackage: _pkg);
  static const IconData thumbUpO =
      IconData(0xe6cb, fontFamily: _family, fontPackage: _pkg);
  static const IconData ticket =
      IconData(0xe800, fontFamily: _family, fontPackage: _pkg);
  static const IconData ticketO =
      IconData(0xe701, fontFamily: _family, fontPackage: _pkg);
  static const IconData time =
      IconData(0xe6f8, fontFamily: _family, fontPackage: _pkg);
  static const IconData timeO =
      IconData(0xe6f9, fontFamily: _family, fontPackage: _pkg);
  static const IconData timer =
      IconData(0xe69c, fontFamily: _family, fontPackage: _pkg);
  static const IconData title =
      IconData(0xe82f, fontFamily: _family, fontPackage: _pkg);
  static const IconData titles =
      IconData(0xe745, fontFamily: _family, fontPackage: _pkg);
  static const IconData toggle =
      IconData(0xe706, fontFamily: _family, fontPackage: _pkg);
  static const IconData toggleO =
      IconData(0xe733, fontFamily: _family, fontPackage: _pkg);
  static const IconData topbar =
      IconData(0xe788, fontFamily: _family, fontPackage: _pkg);
  static const IconData translate =
      IconData(0xe79a, fontFamily: _family, fontPackage: _pkg);
  static const IconData tree =
      IconData(0xe659, fontFamily: _family, fontPackage: _pkg);
  static const IconData tt =
      IconData(0xe7a2, fontFamily: _family, fontPackage: _pkg);
  static const IconData twiter =
      IconData(0xe6e8, fontFamily: _family, fontPackage: _pkg);
  static const IconData ciconCommunityO =
      IconData(0xe6df, fontFamily: _family, fontPackage: _pkg);
  static const IconData undo =
      IconData(0xe61b, fontFamily: _family, fontPackage: _pkg);
  static const IconData unfoldLess =
      IconData(0xe60e, fontFamily: _family, fontPackage: _pkg);
  static const IconData unfoldMore =
      IconData(0xe609, fontFamily: _family, fontPackage: _pkg);
  static const IconData upstage =
      IconData(0xe724, fontFamily: _family, fontPackage: _pkg);
  static const IconData upstageO =
      IconData(0xe725, fontFamily: _family, fontPackage: _pkg);
  static const IconData viewAgenda =
      IconData(0xe639, fontFamily: _family, fontPackage: _pkg);
  static const IconData viewArray =
      IconData(0xe636, fontFamily: _family, fontPackage: _pkg);
  static const IconData viewCarousel =
      IconData(0xe638, fontFamily: _family, fontPackage: _pkg);
  static const IconData viewColumn =
      IconData(0xe632, fontFamily: _family, fontPackage: _pkg);
  static const IconData viewDay =
      IconData(0xe627, fontFamily: _family, fontPackage: _pkg);
  static const IconData viewHeadline =
      IconData(0xe62b, fontFamily: _family, fontPackage: _pkg);
  static const IconData viewList =
      IconData(0xe63c, fontFamily: _family, fontPackage: _pkg);
  static const IconData viewModule =
      IconData(0xe629, fontFamily: _family, fontPackage: _pkg);
  static const IconData viewQuilt =
      IconData(0xe630, fontFamily: _family, fontPackage: _pkg);
  static const IconData volume =
      IconData(0xe6c4, fontFamily: _family, fontPackage: _pkg);
  static const IconData volumeOff =
      IconData(0xe6cd, fontFamily: _family, fontPackage: _pkg);
  static const IconData warn =
      IconData(0xe662, fontFamily: _family, fontPackage: _pkg);
  static const IconData warnO =
      IconData(0xe675, fontFamily: _family, fontPackage: _pkg);
  static const IconData wechatPay =
      IconData(0xe7e6, fontFamily: _family, fontPackage: _pkg);
  static const IconData weiboFill =
      IconData(0xe7e4, fontFamily: _family, fontPackage: _pkg);
  static const IconData weiboO =
      IconData(0xe7e3, fontFamily: _family, fontPackage: _pkg);
  static const IconData weixin =
      IconData(0xe6de, fontFamily: _family, fontPackage: _pkg);
  static const IconData whatshot =
      IconData(0xe6ca, fontFamily: _family, fontPackage: _pkg);
  static const IconData whatshotO =
      IconData(0xe6d0, fontFamily: _family, fontPackage: _pkg);
  static const IconData wifi =
      IconData(0xe6d2, fontFamily: _family, fontPackage: _pkg);
  static const IconData wifiOff =
      IconData(0xe6d3, fontFamily: _family, fontPackage: _pkg);
  static const IconData yamaxun =
      IconData(0xe7b7, fontFamily: _family, fontPackage: _pkg);
  static const IconData zuoji =
      IconData(0xe754, fontFamily: _family, fontPackage: _pkg);
}